<?php

namespace Asmodine\FrontBundle\Repository;

/**
 * BrandRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository
{
}
