# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt))/
            security: false

        assets:
            pattern: ^/(css|img|js|videos)/
            security: false

        asmodine_api:
            pattern: ^(/api/back/).*$
            stateless: true
            simple_preauth:
                authenticator: asmodine.common.api_server

        api_login:
            pattern:  ^/api/user/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path: /api/user/login_check
                username_parameter: _username
                password_parameter: _password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api_user:
            pattern:   ^/api/user
            provider: fos_userbundle
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /user/login
                check_path: /user/login_check
                success_handler: asmodine.front.security.authentication_success_handler
            logout:
                path: /user/logout
                target: /
            anonymous:    true

        login:
            pattern:  ^/login$
            security: false

            remember_me:
                secret: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/api/user/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/user, roles: [ IS_AUTHENTICATED_FULLY ] }